name: Feature Request
description: Propor uma nova funcionalidade
title: "[feat] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problema
    attributes:
      label: Problema / contexto
      description: Qual problema a feature resolve?
    validations:
      required: true
  - type: textarea
    id: proposta
    attributes:
      label: Proposta
      description: Comportamento esperado, critérios de aceite.
    validations:
      required: true
  - type: textarea
    id: alternativas
    attributes:
      label: Alternativas consideradas
    validations:
      required: false
