"""alter setor to text

Revision ID: 0e974bdce17a
Revises: 001
Create Date: 2026-04-28 18:43:44.514729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0e974bdce17a'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_diagnostico_lead'), table_name='diagnostico')
    op.drop_index(op.f('idx_info_contato_lead'), table_name='info_internet_contato')
    op.alter_column('info_internet_empresa', 'setor',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('idx_info_empresa_lead'), table_name='info_internet_empresa')
    op.drop_index(op.f('idx_interacoes_lead'), table_name='interacoes_chatboot')
    op.alter_column('lead', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('lead', 'posicao_pergunta',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('idx_lead_numero'), table_name='lead')
    op.drop_index(op.f('idx_lead_status'), table_name='lead')
    op.drop_constraint(op.f('lead_numero_whatsapp_key'), 'lead', type_='unique')
    op.create_index(op.f('ix_lead_numero_whatsapp'), 'lead', ['numero_whatsapp'], unique=True)
    op.alter_column('perguntas_diagnostico', 'validada',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('idx_perguntas_lead'), table_name='perguntas_diagnostico')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_perguntas_lead'), 'perguntas_diagnostico', ['lead_id'], unique=False)
    op.alter_column('perguntas_diagnostico', 'validada',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_lead_numero_whatsapp'), table_name='lead')
    op.create_unique_constraint(op.f('lead_numero_whatsapp_key'), 'lead', ['numero_whatsapp'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_lead_status'), 'lead', ['status'], unique=False)
    op.create_index(op.f('idx_lead_numero'), 'lead', ['numero_whatsapp'], unique=False)
    op.alter_column('lead', 'posicao_pergunta',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('lead', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_index(op.f('idx_interacoes_lead'), 'interacoes_chatboot', ['lead_id'], unique=False)
    op.create_index(op.f('idx_info_empresa_lead'), 'info_internet_empresa', ['lead_id'], unique=False)
    op.alter_column('info_internet_empresa', 'setor',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.create_index(op.f('idx_info_contato_lead'), 'info_internet_contato', ['lead_id'], unique=False)
    op.create_index(op.f('idx_diagnostico_lead'), 'diagnostico', ['lead_id'], unique=False)
    # ### end Alembic commands ###